# Generated by Django 5.2.7 on 2025-10-06 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_booking_created_at_booking_customer_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="time",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.availability",
                unique=True,
            ),
        ),
    ]
